### ISSUE TITLE
fm radio app crashes and Xperia xposed module not working properly 

### ISSUE THREAD

**Issue by pavansaragadam** [rovo89/android_art#33]
Hello sir,my fm radio app fc everytime
Here below iam attaching logcat of fmradio app
And if this problem is not related to xposed please accept my apologies and ignore the post
# 3C Toolbox (logcat)

I/16:57:30.055 ActivityManager( 1552)
Process com.sonyericsson.fmradio (pid 26747) has died
I/16:57:30.035 Process (26747)
Sending signal. PID: 26747 SIG: 9
E/16:57:28.788 AndroidRuntime(26747)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
E/16:57:28.788 AndroidRuntime(26747)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
E/16:57:28.788 AndroidRuntime(26747)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E/16:57:28.788 AndroidRuntime(26747)
    at java.lang.reflect.Method.invoke(Method.java:372)
E/16:57:28.788 AndroidRuntime(26747)
    at java.lang.reflect.Method.invoke(Native Method)
E/16:57:28.788 AndroidRuntime(26747)
    at android.app.ActivityThread.main(ActivityThread.java:5373)
E/16:57:28.788 AndroidRuntime(26747)
    at android.os.Looper.loop(Looper.java:211)
E/16:57:28.788 AndroidRuntime(26747)
    at android.os.Handler.dispatchMessage(Handler.java:102)
E/16:57:28.788 AndroidRuntime(26747)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
E/16:57:28.788 AndroidRuntime(26747)
    at android.app.ActivityThread.access$800(ActivityThread.java:156)
E/16:57:28.788 AndroidRuntime(26747)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
E/16:57:28.788 AndroidRuntime(26747)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
E/16:57:28.788 AndroidRuntime(26747)
    at android.app.Activity.performStart(Activity.java:6006)
E/16:57:28.788 AndroidRuntime(26747)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
E/16:57:28.788 AndroidRuntime(26747)
    at com.sonyericsson.fmradio.ui.FmRadioActivity.onStart(FmRadioActivity.java:250)
E/16:57:28.788 AndroidRuntime(26747)
    at com.sonyericsson.fmradio.ui.FmRadioActivity.connectToFmService(FmRadioActivity.java:449)
E/16:57:28.788 AndroidRuntime(26747)
    at com.sonyericsson.fmradio.ui.FmRadioFeedback.<init>(FmRadioFeedback.java:63)
E/16:57:28.788 AndroidRuntime(26747)
java.lang.NoClassDefFoundError: com.sonyericsson.fmradio.service.FmService
E/16:57:28.788 AndroidRuntime(26747)
Process: com.sonyericsson.fmradio, PID: 26747
E/16:57:28.788 AndroidRuntime(26747)
FATAL EXCEPTION: main
D/16:57:28.786 AndroidRuntime(26747)
Shutting down VM
I/16:57:28.786 art     (26747)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/16:57:28.782 art     (26747)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/16:57:28.782 art     (26747)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/16:57:28.782 art     (26747)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/16:57:28.782 art     (26747)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/16:57:28.781 art     (26747)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/16:57:28.779 art     (26747)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/16:57:28.779 art     (26747)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>

**Comment by rovo89** [comment]
Seems to be fixed with v83 according to http://forum.xda-developers.com/xposed/discussion-xposed-marshmallow-t3249095/post66536906
If not, please reopen with a full logcat of the crash.
