### ISSUE TITLE
reference to #33 fm radio app fc and clash of clans game fc

### ISSUE THREAD

**Issue by pavansaragadam** [rovo89/android_art#40]
New problem-on new version xposed 84 clash of clans getting fc on startup but still working...just fc on startup
Old problem-fm radio app is not working... Fc
05-10 09:10:11.221 I/Xposed  (  565): -----------------
05-10 09:10:11.221 I/Xposed  (  565): Starting Xposed version 84, compiled for SDK 22
05-10 09:10:11.221 I/Xposed  (  565): Device: D5322 (Sony), Android version 5.1.1 (SDK 22)
05-10 09:10:11.221 I/Xposed  (  565): ROM: 19.4.A.0.182
05-10 09:10:11.221 I/Xposed  (  565): Build fingerprint: Sony/D5322/D5322:5.1.1/19.4.A.0.182/2188515266:user/release-keys
05-10 09:10:11.221 I/Xposed  (  565): Platform: armeabi-v7a, 32-bit binary, system server: yes
05-10 09:10:11.221 I/Xposed  (  565): SELinux enabled: yes, enforcing: no
05-10 09:10:13.862 I/Xposed  (  565): -----------------
05-10 09:10:13.865 I/Xposed  (  565): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-10 09:10:14.372 I/Xposed  (  565): Detected ART runtime
05-10 09:10:14.408 I/Xposed  (  565): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-10 09:10:14.814 I/Xposed  (  565): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LACK-1/base.apk
05-10 09:10:15.821 I/Xposed  (  565):   Loading class com.chelpus.XSupport
05-10 09:10:15.865 I/Xposed  (  565): Loading modules from /data/app/serajr.xx.lp-1/base.apk
05-10 09:10:16.111 I/Xposed  (  565):   Loading class serajr.xx.lp.Xposed
05-10 09:10:16.149 I/Xposed  (  565): Loading modules from /data/app/serajr.xperia.home.xposed.mm-2/base.apk
05-10 09:10:16.281 I/Xposed  (  565):   Loading class serajr.xperia.home.xposed.mm.Xposed
05-10 09:10:16.302 I/Xposed  (  565): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
05-10 09:10:16.344 I/Xposed  (  565):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
05-10 09:10:16.361 I/Xposed  (  565): Loading modules from /data/app/at.jclehner.appopsxposed-1/base.apk
05-10 09:10:16.391 I/Xposed  (  565):   Loading class at.jclehner.appopsxposed.AppOpsXposed
05-10 09:10:16.428 I/Xposed  (  565): Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1/base.apk
05-10 09:10:16.451 I/Xposed  (  565):   Loading class de.robv.android.xposed.mods.appsettings.XposedMod
05-10 09:10:16.490 I/Xposed  (  565): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
05-10 09:10:17.064 I/Xposed  (  565):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
05-10 09:10:17.091 I/Xposed  (  565):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
05-10 09:10:17.092 I/Xposed  (  565): Loading modules from /data/app/com.tonymanou.screenfilter-1/base.apk
05-10 09:10:17.117 I/Xposed  (  565):   Loading class com.tonymanou.screenfilter.FilterXposed
05-10 09:10:19.781 I/Xposed  ( 1372): Amplify: Version 3.3.6c
05-10 09:10:19.782 I/Xposed  ( 1372): Amplify: Attempting 19to21 AlarmHook
05-10 09:10:19.783 I/Xposed  ( 1372): Amplify: Standard Alarm hook failed.  Trying alternate for Sony device.
05-10 09:10:19.784 I/Xposed  ( 1372): Amplify: Successful 19to21 AlarmHook
05-10 09:10:19.784 I/Xposed  ( 1372): Amplify: Attempting 21 WakeLockHook
05-10 09:10:19.787 I/Xposed  ( 1372): Amplify: Successful 21 WakeLockHook
05-10 09:10:19.787 I/Xposed  ( 1372): Amplify: Service Blocking Status: true
05-10 09:10:19.787 I/Xposed  ( 1372): Amplify: Attempting 17to 22 ServiceHook
05-10 09:10:19.789 I/Xposed  ( 1372): Amplify: Successful 17to 22 ServiceHook
05-10 09:10:40.695 I/Xposed  ( 1372): Screen Filter: registering service on SDK 22...
05-10 09:10:40.706 I/Xposed  ( 1372): Screen Filter: service successfully registered (1.5.2)
05-10 09:10:42.563 W/Xposed  ( 1372): Package name for /data/app/serajr.xperia.home.xposed.mm-2/base.apk had to be retrieved via parser
05-10 09:10:45.092 W/Xposed  ( 1606): Package name for /data/app/serajr.xperia.home.xposed.mm-2/base.apk had to be retrieved via parser
05-10 09:10:47.941 I/Xposed  ( 1626): Screen Filter: com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView()
05-10 09:10:47.995 I/Xposed  ( 1626): Screen Filter: overlay successfully added
05-10 09:10:54.119 W/Xposed  ( 2490): Package name for /data/app/serajr.xx.lp-1/base.apk had to be retrieved via parser
05-10 09:11:35.451 I/XposedInstaller( 4771): Downloaded http://dl.xposed.info/repo/full.xml.gz with status 0 (error: null), size 993610 bytes
05-10 09:11:41.049 I/XposedInstaller( 4771): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 8300 (865 new / 0 removed modules)
05-10 09:14:26.981 F/libc    ( 7004): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 7022 (ll.clashofclan)
05-10 09:14:30.570 W/Xposed  ( 2295): Package name for /data/app/serajr.xx.lp-1/base.apk had to be retrieved via parser
05-10 09:26:21.577 I/Xposed  ( 1372): Amplify: Allowing Alarm com.google.android.gms.icing.proxy.action.SMS_CHANGED.  Max Interval: 240000 Time since last granted: 982240
05-10 09:39:07.279 W/Xposed  (25214): Package name for /data/app/serajr.xperia.home.xposed.mm-2/base.apk had to be retrieved via parser
05-10 09:46:22.195 F/libc    (28235): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 28251 (ll.clashofclan)
05-10 10:16:08.737 W/Xposed  (11603): Package name for /data/app/serajr.xx.lp-1/base.apk had to be retrieved via parser
05-10 10:48:04.668 W/Xposed  (32015): Package name for /data/app/serajr.xperia.home.xposed.mm-2/base.apk had to be retrieved via parser
05-10 10:49:24.740 F/libc    ( 1317): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 1349 (ll.clashofclan)
05-10 10:49:27.508 W/Xposed  (28586): Package name for /data/app/serajr.xx.lp-1/base.apk had to be retrieved via parser
05-10 11:13:05.856 I/Xposed  ( 1372): Amplify: Allowing Wakelock wake:com.whatsapp/.AlarmService.  Max Interval: 7200000 Time since last granted: 7386269
05-10 11:13:06.202 I/Xposed  ( 1372): Amplify: Allowing Alarm com.whatsapp.alarm.AVAILABLE_TIMEOUT.  Max Interval: 7200000 Time since last granted: 7386614
05-10 11:19:57.751 I/Xposed  ( 1372): Amplify: Allowing Wakelock ConnectivityService.  Max Interval: 7200000 Time since last granted: 7798164
05-10 12:39:59.257 I/Xposed  ( 1372): Amplify: Allowing Alarm com.google.android.gms.icing.proxy.action.SMS_CHANGED.  Max Interval: 240000 Time since last granted: 11619912
05-10 12:46:41.523 I/Xposed  ( 1372): Amplify: Allowing Wakelock _net_scheduler_.  Max Interval: 7200000 Time since last granted: 13004420

Logcat of fm radio app
# 3C Toolbox (logcat)

I/12:54:53.837 ActivityManager( 1372)
Process com.sonyericsson.fmradio (pid 3086) has died
I/12:54:53.797 Process ( 3086)
Sending signal. PID: 3086 SIG: 9
E/12:54:52.171 AndroidRuntime( 3086)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
E/12:54:52.171 AndroidRuntime( 3086)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
E/12:54:52.171 AndroidRuntime( 3086)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E/12:54:52.171 AndroidRuntime( 3086)
    at java.lang.reflect.Method.invoke(Method.java:372)
E/12:54:52.171 AndroidRuntime( 3086)
    at java.lang.reflect.Method.invoke(Native Method)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.app.ActivityThread.main(ActivityThread.java:5373)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.os.Looper.loop(Looper.java:211)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.os.Handler.dispatchMessage(Handler.java:102)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.app.ActivityThread.access$800(ActivityThread.java:156)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.app.Activity.performStart(Activity.java:6006)
E/12:54:52.171 AndroidRuntime( 3086)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
E/12:54:52.171 AndroidRuntime( 3086)
    at com.sonyericsson.fmradio.ui.FmRadioActivity.onStart(FmRadioActivity.java:250)
E/12:54:52.171 AndroidRuntime( 3086)
    at com.sonyericsson.fmradio.ui.FmRadioActivity.connectToFmService(FmRadioActivity.java:449)
E/12:54:52.171 AndroidRuntime( 3086)
    at com.sonyericsson.fmradio.ui.FmRadioFeedback.<init>(FmRadioFeedback.java:63)
E/12:54:52.171 AndroidRuntime( 3086)
java.lang.NoClassDefFoundError: com.sonyericsson.fmradio.service.FmService
E/12:54:52.171 AndroidRuntime( 3086)
Process: com.sonyericsson.fmradio, PID: 3086
E/12:54:52.171 AndroidRuntime( 3086)
FATAL EXCEPTION: main
D/12:54:52.170 AndroidRuntime( 3086)
Shutting down VM
I/12:54:52.170 art     ( 3086)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/12:54:52.168 art     ( 3086)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/12:54:52.168 art     ( 3086)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/12:54:52.168 art     ( 3086)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/12:54:52.167 art     ( 3086)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/12:54:52.167 art     ( 3086)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/12:54:52.165 art     ( 3086)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
I/12:54:52.165 art     ( 3086)
Rejecting re-init on previously-failed class java.lang.Class<com.sonyericsson.fmradio.service.FmService>
D/12:54:52.075 AndroidLoader( 3086)
xxsetargv0 : com.sonyericsson.fmradio, 565, 3086
D/12:54:51.942 AndroidLoader( 3086)
xxsetargv0 : <pre-initialized>, 565, 3086
D/12:54:51.938 AndroidLoader( 3086)
Bundles: com.supercell.clashofclans
D/12:54:51.938 AndroidLoader( 3086)
parse_and_load: processName is com.sonyericsson.fmradio
D/12:54:51.937 AndroidLoader( 3086)
xxsetargv0 : com.sonyericsson.fmradio, 565, 3086

Thanks inadvance and sorry if I post anything anythingwrong and tell me if u need more logcat

**Comment by rovo89** [comment]
Could you please post a full logcat of the crashes? This page might help you: https://github.com/rovo89/XposedBridge/wiki/Bugs#how-can-i-get-logs
