### ISSUE TITLE
bootloop on v86 & CM-13 (Victara)

### ISSUE THREAD

**Issue by craftyguy** [rovo89/android_art#51]
Please let me know if you need any more info. This is on cm-13 (build 9/05/2016) for Victara.

```
09-05 12:32:59.507  3137  3137 V KeyValueBackupJob: Scheduling k/v pass in 248 minutes
09-05 12:32:59.508  3137  3137 E System  : ******************************************
09-05 12:32:59.508  3137  3137 E System  : ************ Failure starting system services
09-05 12:32:59.508  3137  3137 E System  : java.lang.RuntimeException: Failed to boot service com.android.server.backup.BackupManagerService$Lifecycle: onBootPhase threw an exception during phase 500
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:137)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.SystemServer.startOtherServices(SystemServer.java:1095)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.SystemServer.run(SystemServer.java:291)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.SystemServer.main(SystemServer.java:176)
09-05 12:32:59.508  3137  3137 E System  :  at java.lang.reflect.Method.invoke(Native Method)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-05 12:32:59.508  3137  3137 E System  : Caused by: java.lang.IllegalArgumentException: No such service ComponentInfo{android/com.android.server.backup.KeyValueBackupJob}
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:786)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:831)
09-05 12:32:59.508  3137  3137 E System  :  at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.KeyValueBackupJob.schedule(KeyValueBackupJob.java:76)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.KeyValueBackupJob.schedule(KeyValueBackupJob.java:57)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.BackupManagerService.dataChangedImpl(BackupManagerService.java:8466)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.BackupManagerService.dataChangedImpl(BackupManagerService.java:8435)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.BackupManagerService.addPackageParticipantsLockedInner(BackupManagerService.java:2058)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.BackupManagerService.addPackageParticipantsLocked(BackupManagerService.java:2035)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.BackupManagerService.<init>(BackupManagerService.java:1086)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.Trampoline.initialize(Trampoline.java:74)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.backup.BackupManagerService$Lifecycle.onBootPhase(BackupManagerService.java:345)
09-05 12:32:59.508  3137  3137 E System  :  at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:135)
09-05 12:32:59.508  3137  3137 E System  :  ... 6 more
09-05 12:32:59.508  3137  3137 D AndroidRuntime: Shutting down VM
09-05 12:32:59.509  3137  3137 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
09-05 12:32:59.509  3137  3137 E AndroidRuntime: java.lang.RuntimeException: Failed to boot service com.android.server.backup.BackupManagerService$Lifecycle: onBootPhase threw an exception during phase 500
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:137)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.SystemServer.startOtherServices(SystemServer.java:1095)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.SystemServer.run(SystemServer.java:291)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.SystemServer.main(SystemServer.java:176)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-05 12:32:59.509  3137  3137 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: No such service ComponentInfo{android/com.android.server.backup.KeyValueBackupJob}
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:786)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:831)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.KeyValueBackupJob.schedule(KeyValueBackupJob.java:76)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.KeyValueBackupJob.schedule(KeyValueBackupJob.java:57)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.BackupManagerService.dataChangedImpl(BackupManagerService.java:8466)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.BackupManagerService.dataChangedImpl(BackupManagerService.java:8435)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.BackupManagerService.addPackageParticipantsLockedInner(BackupManagerService.java:2058)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.BackupManagerService.addPackageParticipantsLocked(BackupManagerService.java:2035)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.BackupManagerService.<init>(BackupManagerService.java:1086)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.Trampoline.initialize(Trampoline.java:74)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.backup.BackupManagerService$Lifecycle.onBootPhase(BackupManagerService.java:345)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:135)
09-05 12:32:59.509  3137  3137 E AndroidRuntime:    ... 6 more
09-05 12:32:59.938  3137  3355 D WifiController: DEFERRED_TOGGLE handled


```

**Comment by rovo89** [comment]
As far as I can see from in the stack trace, Xposed isn't even installed, otherwise it would be listed below `ZygoteInit`. If you're sure it's installed properly, please try to deactivate all modules. To me, it rather looks like an issue in the latest nightly (as you reported [here](https://jira.cyanogenmod.org/browse/NIGHTLIES-3344)) or you might have uninstalled/frozen one system app too much.

**Comment by craftyguy** [comment]
yea, you're right. I removed xposed and it still occurs. that was
actually me that filed 3344 after determining it may be a CM issue.
Sorry for the confusion, I'll close this issue!
