### ISSUE TITLE
miui9 oreo v90-beta3 com.android.systemui fc

### ISSUE THREAD

**Issue by i-sususu** [rovo89/android_art#75]
Device (vendor and model):xiaomi mi mix2 
ROM:miui9 8.2.2 china edition based on andorid8.0
Xposed version:v90 beta3
here is the log thanks very much
[error.log](https://github.com/rovo89/android_art/files/1694080/error.log)

**Comment by rovo89** [comment]
```
02-05 13:38:56.678 E/Environment( 2030): Path requests must specify a user by using UserEnvironment
02-05 13:38:56.678 E/Environment( 2030): java.lang.Throwable
02-05 13:38:56.678 E/Environment( 2030): 	at android.os.Environment.throwIfUserRequired(Environment.java:920)
02-05 13:38:56.678 E/Environment( 2030): 	at android.os.Environment.getExternalStorageDirectory(Environment.java:456)
02-05 13:38:56.678 E/Environment( 2030): 	at com.fkzhang.xposed.hook.e.<clinit>(Unknown Source:87)
02-05 13:38:56.678 E/Environment( 2030): 	at com.fkzhang.wechatxposed.XposedInit.handleLoadPackage(Unknown Source:22)
```

Seems to be caused by a module, please disable it.

Also, there might still be issues with MIUI, see my comments here: https://github.com/rovo89/Xposed/issues/317

**Comment by i-sususu** [comment]
I just tried to disable all the modules, but the same result

**Comment by jxgugu** [comment]
楼主你好
我刚才看了一下你的日志
好像。。。。。。。
你装了微X
微X出错误了好像
卸载试试

**Comment by jxgugu** [comment]
回复3楼：
似乎就是miui出了问题
现在有一个情况
miui 安卓8.0用了xp都会无限fc

**Comment by jxgugu** [comment]
@rovo89 
Hey！
Now there is a bug.
In MIUI Android 8.0 or 8.1.
Every MIUI  versions are same.
All can not use the xposed,
I hope you fix the bug or issue a new version.
Thanks

**Comment by odelrio** [comment]
@i-sususu Is it possible to install Xposed in Oreo-based MIUI? I tried several times and it stucks at boot MIX logo.
